// AUTO-GENERATED by generate_decoders.py — do not edit by hand.
// Each method skips through one step's body, advancing the StoryStreamReader
// cursor by exactly the bytes the game's matching Write produced.
// The base StoryStep.conditions[] field is consumed by the dispatcher BEFORE
// calling these methods, so they only read the subclass-specific fields.
namespace DialogExporter;

public static class StepDispatcher_Generated
{
    public static bool TrySkip(byte type, StoryStreamReader r)
    {
        switch (type)
        {
            case 0: // SObjectiveChange
                _ = r.ReadTemplateRefGuid(); // TemplateReference questRef
                _ = r.ReadString(); // string objectiveGuid
                _ = r.ReadInt32(); // ObjectiveState newState
                _ = r.ReadBool(); // bool allowChangeFromFinalStates
                _ = r.ReadBool(); // bool onlyIfActive
                return true;
            case 1: // SActivityEnd
                _ = r.ReadString(); // string activityId
                return true;
            case 2: // SQuestAdd
                _ = r.ReadTemplateRefGuid(); // TemplateReference questRef
                return true;
            case 3: // SQuestComplete
                _ = r.ReadTemplateRefGuid(); // TemplateReference questTemplate
                _ = r.ReadBool(); // bool completeActiveObjectives
                return true;
            case 4: // SQuestFail
                _ = r.ReadTemplateRefGuid(); // TemplateReference questTemplate
                return true;
            case 5: // SQuestFailAllFor
                _ = r.ReadTemplateRefGuid(); // TemplateReference faction
                return true;
            case 6: // SQuestTrack
                _ = r.ReadTemplateRefGuid(); // TemplateReference questRef
                return true;
            case 7: // SActivateNpcPresence
                _ = r.ReadLocationReference(); // LocationReference presences
                _ = r.ReadInt32(); // Mode mode
                _ = r.ReadInt32(); // Travel travel
                return true;
            case 8: // SActivateNpcPresenceTemporarily
                _ = r.ReadInt32(); // Travel travelTo
                _ = r.ReadInt32(); // Travel travelBack
                _ = r.ReadRichLabelUsage(); // RichLabelUsage richLabelUsage
                return true;
            case 9: // SActivateNpcPresenceViaRichLabels
                _ = r.ReadInt32(); // Mode mode
                _ = r.ReadInt32(); // Travel travel
                _ = r.ReadRichLabelUsage(); // RichLabelUsage richLabelUsage
                return true;
            case 10: // SActorState
                _ = r.ReadActorRefGuid(); // ActorRef actorRef
                _ = r.ReadActorStateName(); // ActorStateRef stateName
                return true;
            case 11: // SAnalyticEvent
                _ = r.ReadInt32(); // EventType evtType
                _ = r.ReadInt32(); // GAProgressionStatus progressionType
                _ = r.ReadStringArray(); // string[] parts
                _ = r.ReadFloat(); // float value
                return true;
            case 12: // SArt
                _ = r.ReadSpriteReference(); // SpriteReference art
                return true;
            case 13: // SArthturMemoryReminder
                return true;
            case 14: // SAssignDuelArena
                { _ = r.ReadByte(); _ = r.ReadTemplateRefGuid(); _ = r.ReadSceneReference(); _ = r.ReadByte(); _ = r.ReadStringArray(); _ = r.ReadTemplateRefArray(); _ = r.ReadActorRefArray(); } // DuelArenaReferenceData duelArenaReferenceData
                _ = r.ReadBool(); // bool teleportToArenaScene
                _ = r.ReadBool(); // bool teleportToArena
                _ = r.ReadBool(); // bool teleportOnlySummonsToArena
                _ = r.ReadBool(); // bool automaticallyActivateArena
                return true;
            case 15: // SBlinkHeroEyes
                _ = r.ReadFloat(); // float blinkingDuration
                _ = r.ReadFloat(); // float closedEyesDuration
                return true;
            case 16: // SBookmark
                _ = r.ReadString(); // string flag
                _ = r.ReadBool(); // bool storySettings
                _ = r.ReadBool(); // bool involveHero
                _ = r.ReadBool(); // bool involveAI
                return true;
            case 17: // SBountyGoToJail
                _ = r.ReadLocationReference(); // LocationReference guard
                _ = r.ReadBool(); // bool payNormalBounty
                return true;
            case 18: // SBountyIncrease
                _ = r.ReadTemplateRefGuid(); // TemplateReference owner
                _ = r.ReadBool(); // bool unforgivableCrime
                _ = r.ReadFloat(); // float bountyGain
                _ = r.ReadByte(); // CrimeSituation situation
                return true;
            case 19: // SBountyPayWealth
                _ = r.ReadLocationReference(); // LocationReference guard
                return true;
            case 20: // SBountyReset
                _ = r.ReadLocationReference(); // LocationReference guard
                _ = r.ReadTemplateRefGuid(); // TemplateReference crimeOwnerTemplate
                return true;
            case 21: // SBountyTemporaryStash
                _ = r.ReadLocationReference(); // LocationReference guard
                _ = r.ReadTemplateRefGuid(); // TemplateReference crimeOwnerTemplate
                _ = r.ReadInt32(); // StashAction stashAction
                return true;
            case 22: // SShowChallengeChoice
                _ = r.ReadInt32(); // int debuffPanelStack
                return true;
            case 23: // SShowChallengeRemoval
                _ = r.ReadInt32(); // int debuffPanelStack
                return true;
            case 24: // SShowChallengeScoreBoard
                return true;
            case 25: // SChangeCompassVisibility
                _ = r.ReadString(); // string id
                _ = r.ReadBool(); // bool visible
                return true;
            case 26: // SChangeCurrency
                _ = r.ReadByte(); // CurrencyType currencyType
                _ = r.ReadInt32(); // int amount
                _ = r.ReadBool(); // bool ignoreRequirements
                _ = r.ReadBool(); // bool showInChoice
                _ = r.ReadBool(); // bool notificationUI
                return true;
            case 27: // SChangeHeroMountOwner
                _ = r.ReadLocationReference(); // LocationReference locationRef
                _ = r.ReadBool(); // bool isHeroMount
                return true;
            case 28: // SChangeItemsQuantity
                _ = r.ReadItemSpawningDataArray(); // ItemSpawningData[] itemTemplateReferenceQuantityPairs
                _ = r.ReadStringArray(); // string[] tags
                _ = r.ReadStringArray(); // string[] forbiddenTags
                _ = r.ReadTemplateRefGuid(); // TemplateReference lootTableReference
                { _ = r.ReadBool(); _ = r.ReadByte(); _ = r.ReadByte(); _ = r.ReadByte(); _ = r.ReadInt32(); } // ConditionalInt manualSelection
                _ = r.ReadInt32(); // int taggedQuantity
                _ = r.ReadBool(); // bool allowCancel
                _ = r.ReadBool(); // bool isKnown
                _ = r.ReadBool(); // bool ignoreRequirements
                _ = r.ReadBool(); // bool removeAll
                _ = r.ReadBool(); // bool onlyStolen
                _ = r.ReadChapterIndex(); // StoryChapter leaveChapter
                return true;
            case 29: // SChangeNpcFaction
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool default
                _ = r.ReadTemplateRefGuid(); // TemplateReference faction
                return true;
            case 30: // SChangeVolumeWeight
                _ = r.ReadStringArray(); // string[] tags
                _ = r.ReadInt32(); // int state
                _ = r.ReadBool(); // bool instant
                return true;
            case 31: // SChoice
                _ = r.ReadRuntimeChoice(); // RuntimeChoice choice
                _ = r.ReadFmodGuid(); // EventReference audioClip
                _ = r.ReadString(); // string spanFlag
                _ = r.ReadInt32(); // TimeSpans span
                _ = r.ReadByte(); // ChoiceIcon choiceIcon
                _ = r.ReadBool(); // bool shouldDisplayExitIcon
                _ = r.ReadBool(); // bool shouldDisplayShopIcon
                _ = r.ReadChapterIndex(); // StoryChapter targetChapter
                return true;
            case 32: // SChoiceExit
                _ = r.ReadRuntimeChoice(); // RuntimeChoice choice
                _ = r.ReadFmodGuid(); // EventReference audioClip
                _ = r.ReadString(); // string spanFlag
                _ = r.ReadInt32(); // TimeSpans span
                _ = r.ReadByte(); // ChoiceIcon choiceIcon
                _ = r.ReadBool(); // bool shouldDisplayExitIcon
                _ = r.ReadBool(); // bool shouldDisplayShopIcon
                _ = r.ReadChapterIndex(); // StoryChapter targetChapter
                _ = r.ReadBool(); // bool hiddenFromPlayer
                return true;
            case 33: // SChoiceSubmenu
                _ = r.ReadRuntimeChoice(); // RuntimeChoice choice
                _ = r.ReadFmodGuid(); // EventReference audioClip
                _ = r.ReadString(); // string spanFlag
                _ = r.ReadInt32(); // TimeSpans span
                _ = r.ReadByte(); // ChoiceIcon choiceIcon
                _ = r.ReadBool(); // bool shouldDisplayExitIcon
                _ = r.ReadBool(); // bool shouldDisplayShopIcon
                _ = r.ReadChapterIndex(); // StoryChapter targetChapter
                return true;
            case 34: // SClearStory
                return true;
            case 35: // SCloseHeroEyes
                _ = r.ReadFloat(); // float duration
                return true;
            case 36: // SCommitCrime
                _ = r.ReadTemplateRefGuid(); // TemplateReference owner
                _ = r.ReadFloat(); // float bountyMultiplier
                _ = r.ReadByte(); // SimpleCrimeType crime
                _ = r.ReadBool(); // bool ignoreVisibility
                _ = r.ReadBool(); // bool instantReport
                _ = r.ReadFloat(); // float customBounty
                _ = r.ReadItemSpawningData(); // ItemSpawningData itemData
                _ = r.ReadActorRefGuid(); // ActorRef actorRef
                return true;
            case 37: // SDeactivateTemporarilyActivatedNpcPresence
                return true;
            case 38: // SDialogueBasedCutsceneControl
                { int n = r.ReadInt32(); for (int i = 0; i < n; i++) { _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadBool(); _ = r.ReadByte(); _ = r.ReadByte(); _ = r.ReadByte(); } } // ActionData[] actions
                return true;
            case 39: // SDisableSarrasMap
                return true;
            case 40: // SDiscardSpawnedLocations
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadBool(); // bool discardNormalLocations
                _ = r.ReadBool(); // bool discardWyrdspawnLocations
                return true;
            case 41: // SDiscardUI
                return true;
            case 42: // SDuelActivateArena
                return true;
            case 43: // SDuelAddNewGroup
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadStoryBookmark(); // StoryBookmark callbackOnGroupVictory
                _ = r.ReadBool(); // bool useCallbackLocation
                _ = r.ReadLocationReference(); // LocationReference locationToUseCallback
                _ = r.ReadBool(); // bool overrideDuelistSettings
                { _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadARAssetRef(); } // DuelistSettings settings
                return true;
            case 44: // SDuelAddToGroup
                _ = r.ReadInt32(); // int groupId
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool overrideDuelistSettings
                { _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadARAssetRef(); } // DuelistSettings settings
                return true;
            case 45: // SDuelCreate
                _ = r.ReadBool(); // bool autoStart
                _ = r.ReadBool(); // bool autoEnd
                _ = r.ReadBool(); // bool addHeroToGroup0
                _ = r.ReadBool(); // bool addNpcsToGroup0
                { _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadARAssetRef(); } // DuelistSettings defaultDuelistSettings
                _ = r.ReadLocationReference(); // LocationReference locations0
                _ = r.ReadStoryBookmark(); // StoryBookmark callbackOnGroup0Victory
                _ = r.ReadBool(); // bool useCallbackLocation0
                _ = r.ReadLocationReference(); // LocationReference locationToUseCallback0
                _ = r.ReadLocationReference(); // LocationReference locations1
                _ = r.ReadStoryBookmark(); // StoryBookmark callbackOnGroup1Victory
                _ = r.ReadBool(); // bool useCallbackLocation1
                _ = r.ReadLocationReference(); // LocationReference locationToUseCallback1
                return true;
            case 46: // SDuelManualEnd
                return true;
            case 47: // SDuelManualStart
                return true;
            case 48: // SEmitLogic
                _ = r.ReadLocationReference(); // LocationReference target
                _ = r.ReadByte(); // TargetState targetState
                return true;
            case 49: // SEndAllOtherStories
                _ = r.ReadStringArray(); // string[] guids
                return true;
            case 50: // SEndStory
                _ = r.ReadBool(); // bool stopInvolvingHero
                return true;
            case 51: // SEndStoryIfRequested
                _ = r.ReadBool(); // bool stopInvolvingHero
                return true;
            case 52: // SEndVideoSequence
                return true;
            case 53: // SEnterVoid
                return true;
            case 54: // SExitToMenu
                return true;
            case 55: // SExitVoid
                return true;
            case 56: // SFactionChangeHostility
                _ = r.ReadTemplateRefGuid(); // TemplateReference from
                _ = r.ReadTemplateRefGuid(); // TemplateReference to
                _ = r.ReadInt32(); // Antagonism antagonism
                _ = r.ReadBool(); // bool twoWay
                return true;
            case 57: // SFakeInteractionPrompt
                _ = r.ReadLocString(); // LocString title
                _ = r.ReadLocString(); // LocString description
                return true;
            case 58: // SFancyPanel
                _ = r.ReadLightLocString(); // LightLocString text
                _ = r.ReadRichEnumRefStr(); // RichEnumReference type
                return true;
            case 59: // SFastTravel
                _ = r.ReadBool(); // bool withTransition
                _ = r.ReadString(); // string portalTag
                return true;
            case 60: // SFenceAllItems
                _ = r.ReadFloat(); // float fenceValuePercentageToPay
                return true;
            case 61: // SFlagChange
                _ = r.ReadString(); // string flag
                _ = r.ReadBool(); // bool newState
                return true;
            case 62: // SFlagChangeDelayed
                { _ = r.ReadInt64(); } // ARTimeSpan timeSpan
                _ = r.ReadString(); // string flag
                _ = r.ReadBool(); // bool newState
                return true;
            case 63: // SForceRestockShop
                _ = r.ReadLocationReference(); // LocationReference locationRef
                return true;
            case 64: // SForceShowNotifications
                _ = r.ReadBool(); // bool enable
                return true;
            case 65: // SForgetRecipe
                _ = r.ReadTemplateRefGuid(); // TemplateReference recipe
                return true;
            case 66: // SGiveItemSet
                _ = r.ReadTemplateRefGuid(); // TemplateReference itemSet
                _ = r.ReadBool(); // bool onlyItems
                return true;
            case 67: // SGiveStatus
                _ = r.ReadTemplateRefGuid(); // TemplateReference statusReference
                _ = r.ReadBool(); // bool showStatusPopup
                _ = r.ReadActorRefGuid(); // ActorRef statusGiver
                _ = r.ReadBool(); // bool overrideDuration
                _ = r.ReadFloat(); // float newDuration
                return true;
            case 68: // SGraphJump
                _ = r.ReadStoryBookmark(); // StoryBookmark bookmark
                return true;
            case 69: // SBountyStopInterventions
                return true;
            case 70: // SHeroCameraChangeDamping
                _ = r.ReadFloat(); // float damping
                return true;
            case 71: // SHeroMove
                _ = r.ReadFloat(); // float stoppingDistance
                _ = r.ReadBool(); // bool waitForEnd
                _ = r.ReadInt32(); // TargetType moveToType
                _ = r.ReadLocationReference(); // LocationReference target
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 targetPos
                _ = r.ReadInt32(); // AdditionalOffset moveToOffsetType
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 offset
                _ = r.ReadBool(); // bool rotateTowardsMovement
                _ = r.ReadBool(); // bool usePatrolPath
                _ = r.ReadBool(); // bool moveFromCurrentHeroPosition
                _ = r.ReadString(); // string uniqueID
                return true;
            case 72: // SIncreaseSarrasSickleCharge
                _ = r.ReadFloat(); // float chargeAmount
                return true;
            case 73: // SInvolveHero
                return true;
            case 74: // SJournalUnlock
                _ = r.ReadJournalGuid(); // JournalGuid guid
                _ = r.ReadInt32(); // EntryType entryType
                return true;
            case 75: // SLearnRecipe
                _ = r.ReadTemplateRefGuid(); // TemplateReference recipe
                return true;
            case 76: // SLeave
                return true;
            case 77: // SLocationAddToStory
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool invulnerability
                _ = r.ReadBool(); // bool involve
                _ = r.ReadBool(); // bool rotToHero
                _ = r.ReadBool(); // bool forceExitInteraction
                _ = r.ReadBool(); // bool waitForInvolvement
                return true;
            case 78: // SLocationChangeAttachments
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadInt32(); // ChangeType changeTo
                _ = r.ReadString(); // string groupName
                return true;
            case 79: // SLocationChangeFocus
                _ = r.ReadLocationReference(); // LocationReference focusTarget
                _ = r.ReadByte(); // FocusOverrideType focusType
                return true;
            case 80: // SLocationChangeInteractability
                _ = r.ReadRichEnumRefStr(); // RichEnumReference targetInteractability
                _ = r.ReadLocationReference(); // LocationReference locationReference
                return true;
            case 81: // SLocationClear
                _ = r.ReadLocationReference(); // LocationReference locations
                return true;
            case 82: // SLocationDiscard
                _ = r.ReadLocationReference(); // LocationReference locationReference
                return true;
            case 83: // SLocationInteract
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadBool(); // bool isHeroInteracting
                return true;
            case 84: // SLocationMakeBusy
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadStoryBookmark(); // StoryBookmark busyStory
                { _ = r.ReadInt64(); } // ARTimeSpan busyDuration
                return true;
            case 85: // SLocationMaterialPropertyController
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadBool(); // bool enable
                return true;
            case 86: // SLocationRemoveBusy
                _ = r.ReadLocationReference(); // LocationReference locationReference
                return true;
            case 87: // SLocationRemoveItem
                _ = r.ReadLocationReference(); // LocationReference location
                _ = r.ReadItemSpawningData(); // ItemSpawningData itemData
                return true;
            case 88: // SLocationRunUnobserved
                _ = r.ReadBool(); // bool requireDistance
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadBool(); // bool waitTime
                _ = r.ReadBool(); // bool waitInRealTime
                { _ = r.ReadInt64(); } // ARTimeSpan timeSpan
                _ = r.ReadStoryBookmark(); // StoryBookmark targetStory
                _ = r.ReadBool(); // bool useToPassReference
                _ = r.ReadLocationReference(); // LocationReference toPassReference
                return true;
            case 89: // SLocationStartStory
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadStoryBookmark(); // StoryBookmark bookmark
                return true;
            case 90: // SLockItems
                _ = r.ReadBool(); // bool lockAllItems
                _ = r.ReadBool(); // bool lockAllLoadouts
                _ = r.ReadBool(); // bool lockAllEquipment
                return true;
            case 91: // SLoseAllWyrdSoulFragments
                return true;
            case 92: // SManualAutoSave
                _ = r.ReadBool(); // bool forceSaveRightNow
                return true;
            case 93: // SMapChange
                _ = r.ReadSceneReference(); // SceneReference scene
                _ = r.ReadString(); // string indexTag
                _ = r.ReadBool(); // bool useDefaultPortal
                return true;
            case 94: // SModifyCullingDistanceDuringStory
                _ = r.ReadBool(); // bool removeMultiplier
                _ = r.ReadFloat(); // float multiplierValue
                _ = r.ReadBool(); // bool allowClampOfValues
                return true;
            case 95: // SMoveItemBetweenLocations
                _ = r.ReadItemSpawningData(); // ItemSpawningData itemData
                _ = r.ReadBool(); // bool takeAllCopies
                _ = r.ReadLocationReference(); // LocationReference moveFromLocationRef
                _ = r.ReadBool(); // bool toHeroEq
                _ = r.ReadLocationReference(); // LocationReference moveToLocationRef
                return true;
            case 96: // SNodeJump
                _ = r.ReadString(); // string spanFlag
                _ = r.ReadInt32(); // TimeSpans span
                _ = r.ReadChapterIndex(); // StoryChapter targetChapter
                return true;
            case 97: // SNpcChangeCrimeOverride
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool disableCrimes
                return true;
            case 98: // SNpcChangeInvolve
                _ = r.ReadActorRefGuid(); // ActorRef actorRef
                _ = r.ReadBool(); // bool invulnerability
                _ = r.ReadBool(); // bool involve
                _ = r.ReadBool(); // bool rotReturnToInteraction
                _ = r.ReadBool(); // bool rotToHero
                _ = r.ReadBool(); // bool forceExitInteraction
                _ = r.ReadBool(); // bool waitForInvolvement
                return true;
            case 99: // SNpcChangePresence
                _ = r.ReadRichLabelUsage(); // RichLabelUsage richLabelUsage
                _ = r.ReadByte(); // ChangeType changeType
                _ = r.ReadInt32(); // Travel travelMode
                _ = r.ReadInt32(); // Travel returnTravelMode
                _ = r.ReadBool(); // bool invulnerability
                _ = r.ReadBool(); // bool involve
                _ = r.ReadBool(); // bool rotateToHero
                _ = r.ReadBool(); // bool waitForAllFinished
                return true;
            case 100: // SNpcGiveItem
                _ = r.ReadActorRefGuid(); // ActorRef actorRef
                _ = r.ReadItemSpawningData(); // ItemSpawningData itemData
                _ = r.ReadBool(); // bool equip
                return true;
            case 101: // SNpcKill
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool markDeathAsNonCriminal
                _ = r.ReadBool(); // bool allowPrevention
                _ = r.ReadBool(); // bool keepBodyForever
                return true;
            case 102: // SNpcLookAt
                _ = r.ReadBool(); // bool waitForEnd
                _ = r.ReadLocationReference(); // LocationReference source
                _ = r.ReadInt32(); // TargetType lookAtType
                _ = r.ReadLocationReference(); // LocationReference target
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 targetPos
                return true;
            case 103: // SNpcMove
                _ = r.ReadFloat(); // float stoppingDistance
                _ = r.ReadBool(); // bool waitForEnd
                _ = r.ReadInt32(); // TargetType moveToType
                _ = r.ReadLocationReference(); // LocationReference target
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 targetPos
                _ = r.ReadInt32(); // AdditionalOffset moveToOffsetType
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 offset
                _ = r.ReadLocationReference(); // LocationReference targets
                _ = r.ReadBool(); // bool shouldUninvolve
                _ = r.ReadBool(); // bool shouldInvolveAfterMoved
                _ = r.ReadRichEnumRefStr(); // RichEnumReference movementType
                return true;
            case 104: // SNpcRefreshCurrentBehaviour
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadBool(); // bool shouldWaitForStart
                return true;
            case 105: // SNpcRemoveItem
                _ = r.ReadActorRefGuid(); // ActorRef actorRef
                _ = r.ReadItemSpawningData(); // ItemSpawningData itemData
                return true;
            case 106: // SNpcRestoreStat
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadRichEnumRefStr(); // RichEnumReference affectedStat
                return true;
            case 107: // SNpcTurnCombatPrevention
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool enablePrevention
                return true;
            case 108: // SNpcTurnFriendly
                _ = r.ReadLocationReference(); // LocationReference locations
                return true;
            case 109: // SNpcTurnFromGhost
                _ = r.ReadLocationReference(); // LocationReference locations
                return true;
            case 110: // SNpcTurnHostile
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool startFight
                _ = r.ReadBool(); // bool allowDeath
                _ = r.ReadBool(); // bool disableCrimes
                _ = r.ReadBool(); // bool markDeathAsNonCriminal
                return true;
            case 111: // SNpcTurnHostileToNpc
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadLocationReference(); // LocationReference locationsToTarget
                _ = r.ReadBool(); // bool startFight
                _ = r.ReadBool(); // bool allowDeath
                _ = r.ReadBool(); // bool disableCrimes
                _ = r.ReadBool(); // bool markDeathAsNonCriminal
                _ = r.ReadBool(); // bool targetHeroAsWell
                _ = r.ReadBool(); // bool allowTargetsDeath
                _ = r.ReadBool(); // bool disableTargetsCrimes
                _ = r.ReadBool(); // bool markTargetsDeathAsNonCriminal
                return true;
            case 112: // SNpcTurnIntoGhost
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool revertable
                return true;
            case 113: // SNpcTurnKillPrevention
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool enablePrevention
                return true;
            case 114: // SOnHoverChoicePreview
                _ = r.ReadLocString(); // LocString proficienciesSetName
                return true;
            case 115: // SOpenGemsUI
                _ = r.ReadChapterIndex(); // StoryChapter targetChapter
                return true;
            case 116: // SOpenHeroEyes
                _ = r.ReadFloat(); // float duration
                return true;
            case 117: // SOpenHouseUnlock
                _ = r.ReadItemSpawningData(); // ItemSpawningData homeKeyItem
                _ = r.ReadShareableSpriteReference(); // ShareableSpriteReference houseSprite
                _ = r.ReadLightLocString(); // LightLocString houseName
                _ = r.ReadLightLocString(); // LightLocString houseDescription
                _ = r.ReadInt32(); // int price
                _ = r.ReadLocationReference(); // LocationReference portalLocation
                _ = r.ReadBool(); // bool disappearAfterUnlock
                _ = r.ReadStoryBookmark(); // StoryBookmark storyOnUnlock
                return true;
            case 118: // SOpenPopup
                _ = r.ReadByte(); // PopupSize size
                return true;
            case 119: // SOpenSharpeningUI
                return true;
            case 120: // SOpenShop
                _ = r.ReadBool(); // bool bark
                _ = r.ReadLocationReference(); // LocationReference locationRef
                return true;
            case 121: // SOpenSurvey
                return true;
            case 122: // SPerformInteraction
                _ = r.ReadByte(); // InteractionType type
                _ = r.ReadBool(); // bool awaitForPerformStart
                _ = r.ReadBool(); // bool interactionShouldSkipStartAnimation
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadString(); // string uniqueID
                _ = r.ReadStoryBookmark(); // StoryBookmark callback
                return true;
            case 123: // SPerformInteractionAndWait
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadBool(); // bool dropToAnchor
                _ = r.ReadString(); // string uniqueID
                return true;
            case 124: // SPetInteract
                _ = r.ReadLocationReference(); // LocationReference locationRef
                _ = r.ReadByte(); // Interaction interaction
                return true;
            case 125: // SPetSetVariant
                _ = r.ReadLocationReference(); // LocationReference locationRef
                _ = r.ReadTemplateRefGuid(); // TemplateReference variantTemplateRef
                return true;
            case 126: // SPlayerCrouch
                _ = r.ReadBool(); // bool targetState
                _ = r.ReadBool(); // bool revertOnStoryEnd
                _ = r.ReadBool(); // bool useRealCrouch
                _ = r.ReadFloat(); // float duration
                return true;
            case 127: // SPlayGesture
                _ = r.ReadActorRefGuid(); // ActorRef actorRef
                _ = r.ReadString(); // string gestureKey
                _ = r.ReadBool(); // bool waitForEnd
                return true;
            case 128: // SPlayMusic
                _ = r.ReadInt32(); // AudioType managerType
                _ = r.ReadBaseAudioSource(); // BaseAudioSource toPlay
                _ = r.ReadBool(); // bool asOneShot
                return true;
            case 129: // SPlaySFX
                _ = r.ReadLocationReference(); // LocationReference locationRef
                _ = r.ReadFmodGuid(); // EventReference audioClip
                _ = r.ReadBool(); // bool waitForEnd
                return true;
            case 130: // SPlayTutorialVideo
                _ = r.ReadLocString(); // LocString title
                _ = r.ReadLocString(); // LocString text
                _ = r.ReadLoadingHandle(); // LoadingHandle handle
                return true;
            case 131: // SPlayVideo
                _ = r.ReadLoadingHandle(); // LoadingHandle video
                _ = r.ReadInt32(); // Video.TransitionType transitionType
                _ = r.ReadInt32(); // Video.FadeInOptions fadeInOptions
                _ = r.ReadInt32(); // Video.FadeOutOptions fadeOutOptions
                _ = r.ReadBool(); // bool pauseARTime
                return true;
            case 132: // SPlayVideoSet
                _ = r.ReadTemplateRefGuid(); // TemplateReference videoSet
                _ = r.ReadBool(); // bool muteOtherAudio
                return true;
            case 133: // SPopupChoice
                _ = r.ReadRuntimeChoice(); // RuntimeChoice choice
                _ = r.ReadRichEnumRefStr(); // RichEnumReference keyBinding
                _ = r.ReadByte(); // PromptType promptType
                _ = r.ReadChapterIndex(); // StoryChapter targetChapter
                return true;
            case 134: // SRandomMultiple
                _ = r.ReadInt32(); // int pickCount
                return true;
            case 135: // SRandomPick
                _ = r.ReadInt32(); // int weight
                _ = r.ReadString(); // string spanFlag
                _ = r.ReadInt32(); // TimeSpans span
                _ = r.ReadChapterIndex(); // StoryChapter targetChapter
                return true;
            case 136: // SRandomTextShow
                return true;
            case 137: // SRefreshMutableVisibility
                return true;
            case 138: // SRegisterVariableToShow
                _ = r.ReadStringArray(); // string[] context
                ReadCtxArray(r); // Context[] contexts
                _ = r.ReadString(); // string variableName
                return true;
            case 139: // SRemoveAllInteractionOverrides
                _ = r.ReadLocationReference(); // LocationReference locations
                return true;
            case 140: // SReputationProgress
                _ = r.ReadTemplateRefGuid(); // TemplateReference crimeOwner
                _ = r.ReadInt32(); // int value
                _ = r.ReadInt32(); // ReputationType reputationType
                return true;
            case 141: // SResetGuardInterventionCooldown
                _ = r.ReadLocationReference(); // LocationReference guard
                return true;
            case 142: // SRestoreHeroAfterSwap
                _ = r.ReadBool(); // bool cleanCurrentInventory
                return true;
            case 143: // SRestoreStat
                _ = r.ReadRichEnumRefStr(); // RichEnumReference affectedStat
                _ = r.ReadBool(); // bool isKnown
                return true;
            case 144: // SResumeRain
                _ = r.ReadBool(); // bool instant
                return true;
            case 145: // SResurrectNpc
                _ = r.ReadTemplateRefArray(); // TemplateReference[] npcs
                return true;
            case 146: // SSaveChangeAllowed
                _ = r.ReadString(); // string id
                _ = r.ReadBool(); // bool allowed
                return true;
            case 147: // SSetAnimatorParameter
                _ = r.ReadLocationReference(); // LocationReference location
                _ = r.ReadInt32(); // int parameterHash
                _ = r.ReadInt32(); // AnimatorControllerParameterType type
                { _ = r.ReadInt32(); _ = r.ReadBool(); _ = r.ReadByte(); _ = r.ReadByte(); _ = r.ReadByte(); _ = r.ReadFloat(); _ = r.ReadInt32(); } // SavedAnimatorParameter parameter
                return true;
            case 148: // SShakeCamera
                _ = r.ReadFloat(); // float amplitude
                _ = r.ReadFloat(); // float frequency
                _ = r.ReadFloat(); // float time
                _ = r.ReadFloat(); // float pick
                _ = r.ReadBool(); // bool awaitShake
                return true;
            case 149: // SShiftLocationPosition
                _ = r.ReadLocationReference(); // LocationReference locations
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 newPosition
                _ = r.ReadFloat(); // float duration
                _ = r.ReadBool(); // bool waitForCompletion
                _ = r.ReadBool(); // bool relativeShift
                return true;
            case 150: // SShowCredits
                _ = r.ReadBool(); // bool displaySarrasCredits
                _ = r.ReadInt32(); // Video.FadeInOptions fadeIn
                _ = r.ReadInt32(); // Video.TransitionType fadeType
                _ = r.ReadFloat(); // float transitionTime
                return true;
            case 151: // SShowTutorialGraphic
                _ = r.ReadLocString(); // LocString title
                _ = r.ReadLocString(); // LocString text
                _ = r.ReadShareableSpriteReference(); // ShareableSpriteReference handle
                return true;
            case 152: // SShowTutorialText
                _ = r.ReadLocString(); // LocString title
                _ = r.ReadLocString(); // LocString text
                return true;
            case 153: // SSpawnSarrasMessenger
                return true;
            case 154: // SStartCutscene
                _ = r.ReadFloat(); // float toBlackDuration
                _ = r.ReadBool(); // bool discardView
                _ = r.ReadBool(); // bool takeAwayControl
                _ = r.ReadBool(); // bool isTriggeringPortalOnExit
                _ = r.ReadTemplateRefGuid(); // TemplateReference cutscene
                return true;
            case 155: // SStartNewGamePlus
                return true;
            case 156: // SStartTutorial
                _ = r.ReadInt32(); // TutKeys tutorial
                _ = r.ReadBool(); // bool afterStoryEnd
                return true;
            case 157: // SStartVideoSequence
                return true;
            case 158: // SStatChange
                _ = r.ReadByte(); // StoryRoleTarget target
                _ = r.ReadLocationReference(); // LocationReference locationRef
                _ = r.ReadRichEnumRefStr(); // RichEnumReference affectedStat
                _ = r.ReadInt32(); // StatDefinedRange definedRange
                { _ = r.ReadFloat(); _ = r.ReadInt32(); } // StatValue statValue
                _ = r.ReadBool(); // bool isKnown
                _ = r.ReadBool(); // bool isCost
                _ = r.ReadBool(); // bool showStatValue
                _ = r.ReadBool(); // bool showAsPercentage
                _ = r.ReadBool(); // bool useVariableMultiplier
                _ = r.ReadBool(); // bool suppressStatNotification
                return true;
            case 159: // SStatDependantChoice
                _ = r.ReadByte(); // RequirementType requirementType
                _ = r.ReadRichEnumRefStr(); // RichEnumReference affectedStat
                _ = r.ReadFloat(); // float statValue
                _ = r.ReadRichEnumRefStr(); // RichEnumReference comparison
                _ = r.ReadFloat(); // float certainSuccessAtValue
                _ = r.ReadBool(); // bool isVisibleToPlayer
                _ = r.ReadBool(); // bool isChanceVisible
                _ = r.ReadLightLocString(); // LightLocString overrideLabel
                _ = r.ReadChapterIndex(); // StoryChapter successChapter
                return true;
            case 160: // SStatusRemove
                _ = r.ReadTemplateRefArray(); // TemplateReference[] byTemplate
                _ = r.ReadRichEnumRefArray(); // RichEnumReference[] byType
                return true;
            case 161: // SStatusRemoveNpc
                _ = r.ReadLocationReference(); // LocationReference locations
                _ = r.ReadTemplateRefArray(); // TemplateReference[] byTemplate
                _ = r.ReadRichEnumRefArray(); // RichEnumReference[] byType
                return true;
            case 162: // SStopInteraction
                _ = r.ReadLocationReference(); // LocationReference locations
                return true;
            case 163: // SStopInvolvingHero
                return true;
            case 164: // SStopMusic
                _ = r.ReadInt32(); // AudioType managerType
                return true;
            case 165: // SStopRain
                _ = r.ReadBool(); // bool instant
                return true;
            case 166: // SStoryStartChoice
                _ = r.ReadLightLocString(); // LightLocString text
                _ = r.ReadInt32(); // TimeSpans span
                _ = r.ReadString(); // string spanFlag
                _ = r.ReadChapterIndex(); // StoryChapter targetChapter
                return true;
            case 167: // SSwapHero
                _ = r.ReadBool(); // bool cleanCurrentInventory
                { _ = r.ReadBool(); _ = r.ReadByte(); _ = r.ReadByte(); _ = r.ReadByte(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); _ = r.ReadInt32(); } // CharacterPresetData visualPresetData
                { _ = r.ReadInt32(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); _ = r.ReadFmodGuid(); } // AliveAudioContainer aliveAudioContainer
                return true;
            case 168: // STeleportHero
                _ = r.ReadInt32(); // TeleportType teleportType
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 position
                _ = r.ReadLocationReference(); // LocationReference locRef
                _ = r.ReadBool(); // bool overrideRotation
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 rotation
                return true;
            case 169: // STeleportHeroOnHeroDeath
                _ = r.ReadBool(); // bool removeElement
                _ = r.ReadStoryBookmark(); // StoryBookmark bookmark
                _ = r.ReadSceneReference(); // SceneReference sceneReference
                _ = r.ReadString(); // string sceneIndex
                _ = r.ReadBool(); // bool discardOnSceneChange
                return true;
            case 170: // STeleportNpc
                _ = r.ReadLocationReference(); // LocationReference npcToTeleport
                _ = r.ReadInt32(); // TeleportType teleportType
                { _ = r.ReadFloat(); _ = r.ReadFloat(); _ = r.ReadFloat(); } // Vector3 position
                _ = r.ReadLocationReference(); // LocationReference locRef
                return true;
            case 171: // STeleportSummons
                _ = r.ReadFloat(); // float distanceFromHero
                return true;
            case 172: // SText
                _ = r.ReadActorRefGuid(); // ActorRef actorRef
                _ = r.ReadActorRefGuid(); // ActorRef targetActorRef
                _ = r.ReadBool(); // bool lookAtOnlyWithHead
                _ = r.ReadLightLocString(); // LightLocString text
                _ = r.ReadString(); // string gestureKey
                _ = r.ReadFmodGuid(); // EventReference audioClip
                _ = r.ReadBool(); // bool hasVoice
                _ = r.ReadBool(); // bool overrideDuration
                _ = r.ReadInt32(); // int cutDurationMilliseconds
                _ = r.ReadEmotionDataArray(); // EmotionData[] emotions
                return true;
            case 173: // STextCq
                _ = r.ReadActorRefGuid(); // ActorRef actorRef
                _ = r.ReadActorRefGuid(); // ActorRef targetActorRef
                _ = r.ReadBool(); // bool lookAtOnlyWithHead
                _ = r.ReadLightLocString(); // LightLocString text
                _ = r.ReadString(); // string gestureKey
                _ = r.ReadFmodGuid(); // EventReference audioClip
                _ = r.ReadBool(); // bool hasVoice
                _ = r.ReadBool(); // bool overrideDuration
                _ = r.ReadInt32(); // int cutDurationMilliseconds
                _ = r.ReadEmotionDataArray(); // EmotionData[] emotions
                _ = r.ReadShareableSpriteReference(); // ShareableSpriteReference iconRef
                return true;
            case 174: // STimeBlock
                _ = r.ReadString(); // string id
                _ = r.ReadInt32(); // TimeType timeType
                _ = r.ReadBool(); // bool enable
                return true;
            case 175: // STimelinePlay
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadShareableARAssetReference(); // ShareableARAssetReference playableAssetReference
                return true;
            case 176: // STimeSet
                _ = r.ReadInt32(); // int hour
                _ = r.ReadInt32(); // int minutes
                return true;
            case 177: // SToggleManualDissolve
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadBool(); // bool state
                return true;
            case 178: // STransitionToBlack
                _ = r.ReadFloat(); // float duration
                return true;
            case 179: // STransitionToCamera
                _ = r.ReadFloat(); // float duration
                return true;
            case 180: // STrespassingIgnoreTimeToCrime
                return true;
            case 181: // STrespassingRecalculate
                return true;
            case 182: // STrespassingResetTimeToCrime
                _ = r.ReadLocationReference(); // LocationReference guard
                _ = r.ReadBool(); // bool overrideTimeToCrime
                _ = r.ReadFloat(); // float timeToCrime
                return true;
            case 183: // STrespassingResetWarning
                _ = r.ReadLocationReference(); // LocationReference guard
                return true;
            case 184: // STriggerChangeGroupSpawnerToAutomatic
                _ = r.ReadLocationReference(); // LocationReference locationReference
                return true;
            case 185: // STriggerLocationSpawnerAndAddToDuel
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadInt32(); // int groupId
                _ = r.ReadBool(); // bool overrideDuelistSettings
                { _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadBool(); _ = r.ReadARAssetRef(); } // DuelistSettings settings
                return true;
            case 186: // STriggerLocationSpawners
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadBool(); // bool waitForSpawn
                _ = r.ReadBool(); // bool forceCombatWithHero
                return true;
            case 187: // STriggerLocationVS
                _ = r.ReadInt32(); // VSCustomEvent actionType
                _ = r.ReadLocationReference(); // LocationReference locationReference
                return true;
            case 188: // STriggerPortal
                _ = r.ReadLocationReference(); // LocationReference locRef
                _ = r.ReadBool(); // bool waitForTeleport
                return true;
            case 189: // STriggerVFXSpawn
                _ = r.ReadLocationReference(); // LocationReference locationReference
                _ = r.ReadShareableARAssetReference(); // ShareableARAssetReference vfxAssetRef
                _ = r.ReadFloat(); // float vfxDuration
                return true;
            case 190: // STutorialShow
                _ = r.ReadInt32(); // TutKeys tutorial
                return true;
            case 191: // SUnlockItems
                _ = r.ReadBool(); // bool unlockAllItems
                _ = r.ReadBool(); // bool unlockAllLoadouts
                _ = r.ReadBool(); // bool unlockAllEquipment
                return true;
            case 192: // SUnlockSkipPrologue
                return true;
            case 193: // SUnlockWyrdSoulFragment
                _ = r.ReadByte(); // WyrdSoulFragmentType fragmentType
                return true;
            case 194: // SVariableAdd
                _ = r.ReadStringArray(); // string[] context
                ReadCtxArray(r); // Context[] contexts
                _ = r.ReadVariable(); // Variable var
                _ = r.ReadString(); // string comment
                return true;
            case 195: // SVariableCopy
                _ = r.ReadStringArray(); // string[] context
                ReadCtxArray(r); // Context[] contexts
                _ = r.ReadVariable(); // Variable var
                _ = r.ReadString(); // string comment
                _ = r.ReadStringArray(); // string[] contextFrom
                ReadCtxArray(r); // Context[] contextsFrom
                _ = r.ReadVariable(); // Variable variableFrom
                return true;
            case 196: // SVariableMultiply
                _ = r.ReadStringArray(); // string[] context
                ReadCtxArray(r); // Context[] contexts
                _ = r.ReadVariable(); // Variable var
                _ = r.ReadString(); // string comment
                return true;
            case 197: // SVariableReference
                _ = r.ReadStringArray(); // string[] context
                ReadCtxArray(r); // Context[] contexts
                _ = r.ReadVariable(); // Variable var
                _ = r.ReadString(); // string comment
                return true;
            case 198: // SVariableSet
                _ = r.ReadStringArray(); // string[] context
                ReadCtxArray(r); // Context[] contexts
                _ = r.ReadVariable(); // Variable var
                _ = r.ReadString(); // string comment
                return true;
            case 199: // SVariableSetFromItemQuantity
                _ = r.ReadStringArray(); // string[] context
                ReadCtxArray(r); // Context[] contexts
                _ = r.ReadVariable(); // Variable var
                _ = r.ReadString(); // string comment
                return true;
            case 200: // SVariableSum
                _ = r.ReadStringArray(); // string[] context
                ReadCtxArray(r); // Context[] contexts
                _ = r.ReadVariable(); // Variable var
                _ = r.ReadString(); // string comment
                _ = r.ReadStringArray(); // string[] secondContext
                ReadCtxArray(r); // Context[] secondContexts
                _ = r.ReadVariable(); // Variable secondVar
                return true;
            case 201: // SWaitForDelay
                _ = r.ReadFloat(); // float duration
                _ = r.ReadBool(); // bool cancelable
                _ = r.ReadBool(); // bool consumeInput
                _ = r.ReadBool(); // bool useUnscaledTime
                return true;
            case 202: // SWaitForInput
                return true;
            case 203: // SWaitForPopupDiscard
                _ = r.ReadStoryBookmark(); // StoryBookmark bookmark
                return true;
            case 204: // SWeatherSet
                _ = r.ReadInt32(); // int preset
                return true;
            case 205: // SOpenGammaScreen
                return true;
            case 206: // STutorialsClear
                { int n = r.ReadInt32(); for (int i = 0; i < n; i++) { _ = r.ReadInt32(); } } // SequenceKey[] sequencesToClear
                return true;
            default:
                return false;
        }
    }

    private static void ReadCtxArray(StoryStreamReader r)
    {
        int n = r.ReadInt32();
        for (int i = 0; i < n; i++) _ = r.ReadContext();
    }
}
