using System.Text;

namespace DialogExporter;

// Builds a single big lore.txt that's optimised for an LLM to query.
//
// Sections (each prefixed with a clear header):
//   1. Items (name + description + flavor)
//   2. NPCs (display names, where present)
//   3. Quests / Locations / Factions / Talents (anything else with templated names + descriptions)
//   4. Journal & UI / world-text categories (no-template babel keys grouped by region prefix)
//   5. Per-NPC dialogue (grouped by the actor-label resolver, sorted)
//   6. Misc dialogue (anything that didn't get grouped under a single actor)
//
// Plus per-NPC files in `lore/dialog_by_npc/` for direct lookups.

public static class LoreConsolidator
{
    public static void Generate(string outDir, IList<StoryGraphData> graphs, BabelTranslator babel, ActorNameResolver actors)
    {
        var lore = LoreExtractor.ExtractAll(babel);

        // Bucket records by what fields they carry.
        var items     = new List<LoreRecord>();
        var npcs      = new List<LoreRecord>();
        var factions  = new List<LoreRecord>();
        var talents   = new List<LoreRecord>();
        var quests    = new List<LoreRecord>();
        var journals  = new List<LoreRecord>();   // bestiary / lore-encyclopedia / characters / tutorials / fish entries
        var questRecs = new List<LoreRecord>();   // SQ "memorable moment" records (per-ending summaries)
        var others    = new List<LoreRecord>();

        foreach (var rec in lore.Values)
        {
            bool hasItemName    = rec.Fields.ContainsKey("itemName");
            bool hasFactionName = rec.Fields.ContainsKey("factionName");
            bool hasTalentName  = rec.Fields.ContainsKey("talentName");
            bool hasDisplayName = rec.Fields.ContainsKey("displayName");
            bool isNpc          = hasDisplayName && rec.AssetGuid == LoreExtractor.NpcTypeHash;
            bool hasTrackerDesc = rec.Fields.ContainsKey("trackerDescription");

            // Journal entries — Bestiary / Lore / Characters / Tutorials / Fish.
            // These store fields under the "data" wrapper:
            //   data_entryName | data_name → entry title
            //   data_description           → description body
            //   data_subentries_Array_dataN_textToShow → unlockable extra text
            bool isJournal = rec.Fields.ContainsKey("data_description") ||
                             rec.Fields.ContainsKey("data_entryName") ||
                             rec.Fields.ContainsKey("data_name");

            // Quest "records" — per-ending memorable-moment summaries.
            //   records_Array_dataN_text  (e.g. ending text for an SQ)
            bool isQuestRecords = rec.Fields.Keys.Any(f => f.StartsWith("records_Array"));

            if (hasItemName)         items.Add(rec);
            else if (hasFactionName) factions.Add(rec);
            else if (hasTalentName)  talents.Add(rec);
            else if (isNpc)          npcs.Add(rec);
            else if (isJournal)      journals.Add(rec);
            else if (isQuestRecords) questRecs.Add(rec);
            else if (hasDisplayName && (hasTrackerDesc || rec.Fields.ContainsKey("description")))
                                     quests.Add(rec);
            else                     others.Add(rec);
        }

        var loreSb = new StringBuilder();
        WriteHeader(loreSb, "Tainted Grail: Fall of Avalon — Lore Dump");
        loreSb.AppendLine($"Generated by DialogExporter (locale={babel.Locale}). All text is loaded statically from the game's archive files; no runtime is required.");
        loreSb.AppendLine();
        loreSb.AppendLine("Sections:");
        loreSb.AppendLine("  1.  Items (with descriptions and flavor)");
        loreSb.AppendLine("  2.  NPCs (display names)");
        loreSb.AppendLine("  3.  Quests (titles + tracker descriptions)");
        loreSb.AppendLine("  4.  Factions");
        loreSb.AppendLine("  5.  Talents / Skills");
        loreSb.AppendLine("  6.  Encyclopedia / Journal Entries (Bestiary, Lore, Characters, Tutorials, Fish)");
        loreSb.AppendLine("  7.  Quest Memorable Moments (per-ending records)");
        loreSb.AppendLine("  8.  Other Templated Records");
        loreSb.AppendLine("  9.  World Text (UI, stats, keywords, barks)");
        loreSb.AppendLine("  10. Dialogue (grouped by NPC label)");
        loreSb.AppendLine();

        // ------------------------------------------------------- 1) Items
        WriteSection(loreSb, "1. ITEMS");
        foreach (var rec in items.OrderBy(r => Field(r, "itemName")))
        {
            string name = Field(rec, "itemName");
            string desc = Field(rec, "description");
            string flav = Field(rec, "flavor");
            if (string.IsNullOrEmpty(name)) continue;
            loreSb.AppendLine($"### {name}");
            if (!string.IsNullOrEmpty(flav))  loreSb.AppendLine($"_Flavor:_ {flav}");
            if (!string.IsNullOrEmpty(desc))  loreSb.AppendLine(desc);
            loreSb.AppendLine();
        }

        // -------------------------------------------------------- 2) NPCs
        WriteSection(loreSb, "2. NPCs");
        foreach (var rec in npcs.OrderBy(r => Field(r, "displayName")))
        {
            string name = Field(rec, "displayName");
            string desc = Field(rec, "description");
            if (string.IsNullOrEmpty(name)) continue;
            loreSb.AppendLine($"### {name}");
            if (!string.IsNullOrEmpty(desc)) loreSb.AppendLine(desc);
            loreSb.AppendLine();
        }

        // ------------------------------------------------------ 3) Quests
        WriteSection(loreSb, "3. QUESTS");
        foreach (var rec in quests.OrderBy(r => Field(r, "displayName")))
        {
            string name  = Field(rec, "displayName");
            string desc  = Field(rec, "description");
            string track = Field(rec, "trackerDescription");
            if (string.IsNullOrEmpty(name)) continue;
            loreSb.AppendLine($"### {name}");
            if (!string.IsNullOrEmpty(desc))  loreSb.AppendLine(desc);
            if (!string.IsNullOrEmpty(track) && track != desc) loreSb.AppendLine($"_Tracker:_ {track}");
            // Multi-stage objective records show as numbered description fields.
            foreach (var (k, v) in rec.Fields)
            {
                if (k.StartsWith("description#") || k.StartsWith("trackerDescription#"))
                    loreSb.AppendLine($"  • {v}");
            }
            loreSb.AppendLine();
        }

        // ----------------------------------------------------- 4) Factions
        WriteSection(loreSb, "4. FACTIONS");
        foreach (var rec in factions.OrderBy(r => Field(r, "factionName")))
        {
            string name = Field(rec, "factionName");
            string desc = Field(rec, "factionDescription");
            if (string.IsNullOrEmpty(name)) continue;
            loreSb.AppendLine($"### {name}");
            if (!string.IsNullOrEmpty(desc) && desc != "Default faction description") loreSb.AppendLine(desc);
            loreSb.AppendLine();
        }

        // ----------------------------------------------------- 5) Talents
        WriteSection(loreSb, "5. TALENTS / SKILLS");
        foreach (var rec in talents.OrderBy(r => Field(r, "talentName")))
        {
            string name = Field(rec, "talentName");
            string desc = Field(rec, "description");
            string lc   = Field(rec, "lightCastInfo");
            string hc   = Field(rec, "heavyCastInfo");
            if (string.IsNullOrEmpty(name)) continue;
            loreSb.AppendLine($"### {name}");
            if (!string.IsNullOrEmpty(desc)) loreSb.AppendLine(desc);
            if (!string.IsNullOrEmpty(lc))   loreSb.AppendLine($"_Light cast:_ {lc}");
            if (!string.IsNullOrEmpty(hc))   loreSb.AppendLine($"_Heavy cast:_ {hc}");
            loreSb.AppendLine();
        }

        // ----------------------------------- 6) Encyclopedia / Journal entries
        // Bucket by the journal-prefab GUID so Bestiary / Lore / Characters /
        // Tutorials / Fish each get their own block. We label each bucket by
        // the dominant entry (taking the most common entry name as the label
        // is fragile, so we use a "Journal A / B / C ..." sequence).
        WriteSection(loreSb, "6. ENCYCLOPEDIA / JOURNAL ENTRIES");
        var journalsByPrefab = journals.GroupBy(r => r.AssetGuid)
                                       .OrderByDescending(g => g.Count())
                                       .ToList();
        loreSb.AppendLine($"Total journal/encyclopedia entries: {journals.Count}, across {journalsByPrefab.Count} journal prefabs.");
        loreSb.AppendLine();
        char journalLetter = 'A';
        foreach (var bucket in journalsByPrefab)
        {
            // Take the longest description in the bucket as a representative.
            string bucketLabel = $"Journal {journalLetter}  (prefab {bucket.Key}, {bucket.Count()} entries)";
            journalLetter++;
            loreSb.AppendLine($"## {bucketLabel}");
            loreSb.AppendLine();
            foreach (var rec in bucket.OrderBy(r => Field(r, "data_entryName") ?? Field(r, "data_name") ?? GuessTitleFromDescription(Field(r, "data_description")) ?? r.AssetGuid))
            {
                string name = Field(rec, "data_entryName") ?? Field(rec, "data_name");
                string desc = Field(rec, "data_description");
                if (string.IsNullOrEmpty(name) && string.IsNullOrEmpty(desc)) continue;
                // If no explicit title is set, derive one from the first phrase
                // of the description. The Bestiary writers consistently start
                // with the entity name, so this works most of the time.
                string display = name ?? GuessTitleFromDescription(desc) ?? "(no title)";
                loreSb.AppendLine($"### {display}");
                if (!string.IsNullOrEmpty(desc)) loreSb.AppendLine(desc);
                // Sub-entries — additional unlockable lore on this entry.
                var subs = rec.Fields.Where(kv => kv.Key.StartsWith("data_subentries_Array_data") &&
                                                   kv.Key.EndsWith("_textToShow"))
                                     .OrderBy(kv => kv.Key)
                                     .Select(kv => kv.Value)
                                     .ToList();
                if (subs.Count > 0)
                {
                    foreach (var s in subs) loreSb.AppendLine($"  • {s}");
                }
                loreSb.AppendLine();
            }
        }

        // ------------------------------------- 7) Quest Memorable Moments
        // For each completed-story ending the game logs a "memorable moment"
        // — a multi-line summary of how that ending played out. These are
        // serialized as records_Array_dataN_text fields.
        WriteSection(loreSb, "7. QUEST MEMORABLE MOMENTS");
        loreSb.AppendLine($"Total quest-record assets: {questRecs.Count}.");
        loreSb.AppendLine();
        foreach (var rec in questRecs.OrderBy(r => Field(r, "displayName") ?? r.AssetGuid))
        {
            string name = Field(rec, "displayName") ?? Field(rec, "data_displayName") ?? rec.AssetGuid;
            loreSb.AppendLine($"### {name}");
            // record texts in dataN order
            var lines = rec.Fields.Where(kv => kv.Key.StartsWith("records_Array_data") &&
                                                kv.Key.EndsWith("_text"))
                                  .OrderBy(kv => kv.Key)
                                  .Select(kv => kv.Value)
                                  .ToList();
            foreach (var l in lines) loreSb.AppendLine($"  · {l.TrimEnd()}");
            loreSb.AppendLine();
        }

        // -------------------------------------------------------- 8) Other
        WriteSection(loreSb, "8. OTHER TEMPLATED RECORDS");
        foreach (var rec in others.OrderBy(r => Field(r, "displayName") ?? "").ThenBy(r => r.AssetGuid))
        {
            // Anything with at least a description or a name is interesting.
            string label = Field(rec, "displayName") ?? Field(rec, "title") ?? rec.AssetGuid;
            string desc  = Field(rec, "description");
            string flav  = Field(rec, "flavor");
            string lstr  = Field(rec, "locString");
            if (string.IsNullOrEmpty(label) && string.IsNullOrEmpty(desc) && string.IsNullOrEmpty(flav) && string.IsNullOrEmpty(lstr)) continue;
            if (!string.IsNullOrEmpty(label) && label != rec.AssetGuid) loreSb.AppendLine($"### {label}");
            if (!string.IsNullOrEmpty(flav)) loreSb.AppendLine($"_Flavor:_ {flav}");
            if (!string.IsNullOrEmpty(desc)) loreSb.AppendLine(desc);
            if (!string.IsNullOrEmpty(lstr)) loreSb.AppendLine(lstr);
            loreSb.AppendLine();
        }

        // -------------------------------------------------- 9) World Text
        // Babel keys without a Template/ prefix that aren't story dialog.
        WriteSection(loreSb, "9. WORLD TEXT (UI / stats / keywords / barks)");
        var worldText = new SortedDictionary<string, List<(string key, string value)>>();
        for (int i = 0; i < babel.Keys.Length; i++)
        {
            var key = babel.Keys[i];
            var val = babel.Translations[i];
            if (string.IsNullOrEmpty(key) || string.IsNullOrEmpty(val)) continue;
            if (key.StartsWith("Template/")) continue;       // already covered
            if (LooksLikeDialogKey(key)) continue;            // covered in section 8
            int slash = key.IndexOf('/');
            string bucket = slash > 0 ? key[..slash] : "(root)";
            if (!worldText.TryGetValue(bucket, out var list))
                list = worldText[bucket] = new List<(string, string)>();
            list.Add((key, val));
        }
        foreach (var (bucket, list) in worldText.OrderBy(kv => kv.Key))
        {
            loreSb.AppendLine($"### {bucket}  [{list.Count} strings]");
            foreach (var (key, val) in list.OrderBy(p => p.key))
            {
                string trimmed = val.Replace('\r', ' ').Replace('\n', ' ');
                loreSb.AppendLine($"  • {trimmed}");
            }
            loreSb.AppendLine();
        }

        // -------------------------------------------------- 10) Dialogue
        WriteSection(loreSb, "10. DIALOGUE");
        // Group all SText lines by the resolved actor label, then within each
        // group emit per-story sub-sections so context is preserved.
        var dialogByActor = new SortedDictionary<string, List<(StoryGraphData g, ChapterData ch, SaySpeechStep t)>>();
        foreach (var g in graphs)
        {
            if (g.Chapters == null) continue;
            foreach (var ch in g.Chapters)
                foreach (var step in ch.Steps)
                    if (step is SaySpeechStep t)
                    {
                        string label = actors.Resolve(t.ActorGuid);
                        if (string.IsNullOrEmpty(label)) label = "(unknown)";
                        if (!dialogByActor.TryGetValue(label, out var list))
                            list = dialogByActor[label] = new();
                        list.Add((g, ch, t));
                    }
        }

        // Per-NPC files for direct lookup.
        string perNpcDir = Path.Combine(outDir, "dialog_by_npc");
        Directory.CreateDirectory(perNpcDir);
        foreach (var (label, lines) in dialogByActor)
        {
            string fname = SafeFilename(label);
            using var w = new StreamWriter(Path.Combine(perNpcDir, fname + ".txt"));
            w.WriteLine($"# {label}  ({lines.Count} lines)");
            w.WriteLine();
            // Group by story for context; within story sort by chapter index.
            foreach (var grp in lines.GroupBy(x => x.g.Guid).OrderBy(g => g.Key))
            {
                w.WriteLine($"--- story {grp.Key} ---");
                foreach (var (_, ch, t) in grp.OrderBy(x => x.ch.Index))
                {
                    string text = babel.TranslateClean(t.TextId);
                    if (string.IsNullOrWhiteSpace(text)) continue;
                    string target = actors.Resolve(t.TargetActorGuid);
                    w.WriteLine($"  ch{ch.Index} → {target}: {text}");
                }
                w.WriteLine();
            }
        }

        // Inline summary in lore.txt — first 5 lines of each NPC.
        foreach (var (label, lines) in dialogByActor.OrderByDescending(kv => kv.Value.Count))
        {
            loreSb.AppendLine($"### {label}  ({lines.Count} lines, full transcript: dialog_by_npc/{SafeFilename(label)}.txt)");
            int n = 0;
            foreach (var (g, ch, t) in lines.Take(5))
            {
                string text = babel.TranslateClean(t.TextId);
                if (string.IsNullOrWhiteSpace(text)) continue;
                loreSb.AppendLine($"  • {text}");
                n++;
            }
            if (lines.Count > 5) loreSb.AppendLine($"  … and {lines.Count - 5} more lines.");
            loreSb.AppendLine();
        }

        File.WriteAllText(Path.Combine(outDir, "lore.txt"), loreSb.ToString());

        // Also write a separate per-NPC summary index.
        using (var w = new StreamWriter(Path.Combine(outDir, "npcs_index.txt")))
        {
            w.WriteLine("# NPC dialogue index");
            w.WriteLine();
            foreach (var (label, lines) in dialogByActor.OrderByDescending(kv => kv.Value.Count))
                w.WriteLine($"{lines.Count,6}  {label}   →  dialog_by_npc/{SafeFilename(label)}.txt");
        }
    }

    private static string Field(LoreRecord r, string name)
        => r.Fields.TryGetValue(name, out var v) ? v : null;

    // Best-effort: pull a likely entity name out of an encyclopedia description.
    // The Bestiary writers consistently lead with the noun ("Croakmaws are…",
    // "Wyrdspawns are born…"), so the first 1–2 words usually work. For
    // descriptions that begin with a clause, we look for the first proper-noun
    // capitalised word after a comma.
    private static string GuessTitleFromDescription(string desc)
    {
        if (string.IsNullOrWhiteSpace(desc)) return null;
        // First sentence only.
        int dot = desc.IndexOfAny(new[] { '.', '!', '?', '\n' });
        string first = (dot > 0 ? desc[..dot] : desc).Trim();
        if (first.Length == 0) return null;

        // If the sentence starts with a likely subject ("X are/is/was/has/were"),
        // take the leading words up to the verb.
        var verbs = new[] { " are ", " is ", " were ", " was ", " has ", " have ", " did ", " do ", " come ", " comes " };
        foreach (var v in verbs)
        {
            int idx = first.IndexOf(v, StringComparison.Ordinal);
            if (idx > 0) return first[..idx].TrimEnd(',', ' ');
        }
        // Otherwise, look for the first capitalised noun after a comma.
        int comma = first.IndexOf(", ");
        if (comma > 0 && comma + 2 < first.Length)
        {
            string after = first[(comma + 2)..];
            // Take a word phrase up to next space-then-lowercase or up to 30 chars.
            int sp = after.IndexOf(' ');
            if (sp <= 0 || sp > 30) sp = Math.Min(30, after.Length);
            string candidate = after[..sp].TrimEnd(',', '.', ' ');
            if (candidate.Length > 0 && char.IsUpper(candidate[0])) return candidate;
        }
        // Fallback: first 40 chars of the sentence.
        return first.Length <= 40 ? first : first[..40].TrimEnd() + "…";
    }

    private static void WriteHeader(StringBuilder sb, string title)
    {
        sb.AppendLine("=".PadRight(80, '='));
        sb.AppendLine(title);
        sb.AppendLine("=".PadRight(80, '='));
        sb.AppendLine();
    }

    private static void WriteSection(StringBuilder sb, string title)
    {
        sb.AppendLine();
        sb.AppendLine("=".PadRight(80, '='));
        sb.AppendLine(title);
        sb.AppendLine("=".PadRight(80, '='));
        sb.AppendLine();
    }

    private static bool LooksLikeDialogKey(string key)
    {
        // Story dialog keys have the form `<storyName>/<field>_<hash>_<storyGuid>`
        // where <field> is text/choice_text/etc. We exclude those from the
        // world-text dump because they're already in section 8.
        int slash = key.IndexOf('/');
        if (slash <= 0) return false;
        string rest = key[(slash + 1)..];
        return rest.StartsWith("text_") || rest.StartsWith("choice_text_") ||
               rest.StartsWith("choiceText_") || rest.StartsWith("Text_");
    }

    private static string SafeFilename(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var c in s)
            sb.Append(char.IsLetterOrDigit(c) || c == '_' || c == '-' ? c : '_');
        string r = sb.ToString();
        if (r.Length > 80) r = r[..80];
        if (string.IsNullOrEmpty(r)) r = "_";
        return r;
    }
}
